name: WalletAutopilot
description: Wallet health monitoring and automation indexer
ecosystem: evm

networks:
  - id: 41454
    rpc_config:
      url: https://testnet.monad.xyz
    start_block: 0
    contracts:
      - name: ERC20Token
        abi_file_path: ./abis/ERC20.json
        handler: src/handlers/erc20Handler.ts
        address:
          - "0x760AfE86e5de5fa0Ee542fc7B7B713e1c5425701"
          - "0xf817257fed379853cDe0fa4F97AB987181B1E5Ea"
          - "0xb2f82D0f38dc453D596Ad40A37799446Cc89274A"
          - "0x88b8E2161DEDC77EF4ab7585569D2415a1C1055D"
          - "0xE0590015A873bF326bd645c3E1266d4db41C4E6B"

        events:
          - event: Approval(address indexed owner, address indexed spender, uint256 value)
          - event: Transfer(address indexed from, address indexed to, uint256 value)

field_selection:
  transaction_fields:
    - "from"
    - "to"
    - "hash"
    - "transactionIndex"

rollback_on_reorg: true
